name: mlops_lulc
channels:
  - conda-forge
dependencies:
  # required for mlops framework
  - python >3.10,<3.13
  - mlflow
  - apache-airflow
  - psycopg2-binary
  - asyncpg
  - jupyter
  - python-dotenv
  - git
  - fsspec
  - typer
  
  # This is only needed for the examples. If you don't need this, please feel free to remove it.
  - keras
  - tensorflow
  - numpy =2.0.2
  
  # Testing
  - pytest-cov
  - pytest
  # Linting
  - ruff
  - isort
  # add your libraries here
  - pip
  - pip:
      - boto3

