name: mlops_lulc
channels:
  - conda-forge
dependencies:
  - "python >3.10,<3.13"
  - mlflow
  - jupyter
  - python-dotenv
  - git
  - typer

  # SITS (satellite image time series) — wrapper Python sobre R
  - r-base>=4.2
  - r-sits
  - r-arrow
  - r-kohonen
  - r-leaflet
  - r-sf
  - r-htmlwidgets
  - r-tibble
  - r-caret
  - r-torch
  - r-ggplot2
  - gdal
  - proj

  # manipulacao geoespacial e analise de dados
  - geopandas
  - rasterio
  - pandas
  - matplotlib
  - seaborn
  - numpy =2.0.2

  # Testing
  - pytest-cov
  - pytest
  # Linting
  - ruff
  - isort
  - pip
  - pip:
      - pysits
