[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mlops_lulc"
authors = [
    {name = "sandro", email = "sandrosena@alumni.usp.br"},
]
description = "MLOps para classificação de uso e cobertura da terra com SITS e Brazil Data Cube"
version = "0.0.1"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10,<3.13"
dependencies = [
    "pandas",
    "geopandas",
    "rasterio",
    "numpy",
    "matplotlib",
    "seaborn",
    "mlflow",
    "python-dotenv",
    "pysits",
]

[tool.setuptools.packages.find]
exclude = ["notebooks", "data"]

[tool.ruff]
line-length = 100

